name: fatiando-data-sierra-negra-topography
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - numpy
  - jupyterlab
  - matplotlib
  - xarray
  - pyproj
  # for LIDAR data
  - laspy
  - laszip # the C lib
  - pip:
    - laszip # the Python bindinds
  # PyGMT for plotting
  - pygmt==0.4.1
  - gmt==6.2.0
  # Fatiando
  - pooch>=1.0
  - verde==1.6.1
